import '../scss/style.scss'
import '../scss/nav.scss'
import '../scss/nav-1120.scss'
import '../scss/services.scss'
import '../scss/scroll-blocks.scss'
import '../scss/text-and-image.scss'
import '../scss/variables.scss'
import '../scss/section-header-block.scss'
import '../scss/slider.scss'
import '../scss/services-block.scss'
import '../scss/show-more-btn.scss'
import '../js/slider.js'
import '../js/modal.js'
import '../scss/footer.scss'
import '../scss/services-prices.scss'
import '../scss/menu.scss'
import '../scss/contact-form.scss'
import '../scss/call-form.scss'

console.log('Works!')